# fly.toml app configuration file generated for red-snow-2350 on 2023-07-19T04:08:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "red-snow-2350"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
